Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Patisserie.Data;
using Patisserie.Models;

namespace Patisserie.Controllers
{
    public class CategoriesController : Controller
    {
        private PatisserieContext db = new PatisserieContext();

        enum SortBy { popularity=0, priceLTH=1, priceHTL=2 }

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            if (!Utl.IsAdmin(Session)) return RedirectToAction("Index", "Home");

            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Name,ImagePath,Description")] Category category)
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Category category = db.Categories.Find(id);
            if (category == null)  return HttpNotFound();

            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,Name,ImagePath,Description")] Category category)
        {
            if (!Utl.IsAdmin(Session)) return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!Utl.IsAdmin(Session)) return RedirectToAction("Index", "Home");

            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id, int sortBy=(int)SortBy.popularity)
        {
            if (id == null) return RedirectToAction("Index", "Products");

            var productsList = db.Products.Include(p => p.Category)
                .Where(p => p.CategoryID == id);

            switch (sortBy)
            {
                case (int)SortBy.priceHTL:
                    productsList = productsList.OrderByDescending(p => p.Price);
                    break;

                case (int)SortBy.priceLTH:
                    productsList = productsList.OrderBy(p => p.Price);
                    break;

                default:
                    productsList = productsList.OrderByDescending(p => p.PopularityRate);
                    break;
            }

            ViewBag.Category = db.Categories.Where(c => c.CategoryID == id).ToList()[0];
            return View(productsList.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Controllers/FooterController.cs
using Patisserie.Data;
using Patisserie.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Patisserie.Controllers
{
    public class FooterController : Controller
    {
        private readonly PatisserieContext db = new PatisserieContext();

        // GET: Footer
        public ActionResult Index()
        {
            List<Branch> branches = db.Branches.ToList();
            return PartialView("_Footer", branches);
        }
    }
}

Views/Shared/_CartModal.cshtml
<div class="modal fade" id="cart-modal" tabindex="-1" role="dialog" aria-labelledby="CartLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa fa-shopping-cart" aria-hidden="true"></i>My Cart</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-hover table-responsive" id="cart-table"></table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Continue shopping</button>
                <form action="/Orders/SubmitOrder" method="post">
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-success checkout-cart">Checkout</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
        let cart = @Html.Raw(Session["cart"] != null ? Json.Encode((List<object>)Session["cart"]) : "[]");
</script>

<script src="~/Scripts/cart.js" type="text/javascript" defer></script>

Views/Shared/_CategoryCard.cshtml
@model Patisserie.Models.Category

<div class="col-12 col-md-3 card promoting-card px-0 category-card">
    <a href="/Categories/Details/@Html.DisplayFor(modelItem => Model.CategoryID)" class="category-link">
        <img src="~/Media/Images/@Model.ImagePath" alt="@Model.Name" class="card-img card-img-top category-img" />
        <div class="card-body">
            <h2 class="card-title">@Model.Name</h2>
        </div>
    </a>
    @if (Patisserie.Controllers.Utl.IsAdmin(Session))
    {
        <div class="card-footer d-flex justify-content-around flex-row category-footer">
            @Html.ActionLink("Edit", "Edit", "Categories", new { id = Model.CategoryID }, new { @class = "btn btn-outline-secondary" })
            <button class="btn btn-outline-danger btn-delete"
                    data-name="@Model.Name" data-id="@Model.CategoryID">
                Delete
            </button>
        </div>
    }
</div>

Views/Shared/_ContactModal.cshtml
<div class="modal" tabindex="-1" role="dialog" id="contact-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3><i class="fa fa-envelope"></i> Contact us</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="https://mailto:noalecohen1@gmail.com" method="post" target="_top">
                <div class="modal-body">
                    <div class="card-body p-1">

                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                </div>
                                <input type="text" class="form-control" id="contact-name" name="name" placeholder="Full name" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                                </div>
                                <input type="email" class="form-control" id="contact-email" name="email" placeholder="sample@gmail.com" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                                </div>
                                <textarea class="form-control" placeholder="Enter  your message" required></textarea>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Send" class="btn btn-primary rounded-2 py-1">
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/_DeleteModal.cshtml
@{
    string title = this.ViewData.ContainsKey("title") ? this.ViewData["title"].ToString() : string.Empty;
    string category = this.ViewData.ContainsKey("category") ? this.ViewData["category"].ToString() : string.Empty;
}

<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="DeleteLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="delete-title">Are you sure you want to delete ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                <form method="post" id="delete-form">
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(".btn-delete").click(function (e) {
        e.preventDefault();
        e.stopPropagation();

        const title = $(this).data("@title");
        const id = $(this).data("id");

        $("#delete-title").text(`Are you sure you want to delete ${title}?`);
        $("#delete-form").attr("action", `/@category/Delete/${id}`);
        $("#delete-modal").modal('show');
    })
</script>

Views/Shared/_Footer.cshtml
@model List<Patisserie.Models.Branch>

<footer class="footer mt-5 p-2 bg-primary">
    <div class="container">
        <div class="row justify-content-between pt-3">
            <div class="details col-6">
                <h3>Branches</h3>
                <ul class="p-0">
                    <form>
                        @foreach(Patisserie.Models.Branch branch in Model)
                        {
                        <div class="form-check p-0">
                            <input class="form-check-input branch-input" type="radio" 
                                   name="@branch.Name" id="branch-@branch.BranchID" value="@branch.Address">
                            <label class="form-check-label branch-label" for="branch-@branch.BranchID">
                                @branch.Name | @branch.PhoneNumber | @branch.Address
                            </label>
                        </div>
                        }
                    </form>
                </ul>
            </div>
            
            @Html.Partial("_Map", "Map")
        </div>

        <p>&copy; @DateTime.Now.Year - Saar Davidson, Noa Cohen, Iris Kella, Nikol Arazi</p>
    </div>
</footer>

<script>
    $map = $('#gmap_canvas-Map');
    $branchesInput = $('.branch-input');

    $map.attr("src", "https://maps.google.com/maps?q=@Model.First().Address&t=&z=13&ie=UTF8&iwloc=&output=embed")
    $branchesInput.first().prop("checked", true);

    $branchesInput.click(function () {
        $branchesInput.prop("checked", false);
        $(this).prop("checked", true);
        $map.attr("src", 'https://maps.google.com/maps?q=' + $(this).val() + '&t=&z=13&ie=UTF8&iwloc=&output=embed');
    });
</script>

Views/Shared/_Layout.cshtml
@using Patisserie.Controllers

@{
    object accountID;
    object antiForgeryToken;
    if (Utl.IsLoggedIn(Session))
    {
        accountID = Session["accountID"];
        antiForgeryToken = "'" + Html.AntiForgeryToken() + "'";
    }
    else
    {
        accountID = "''";
        antiForgeryToken = "''";
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Noalek</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/774593af2e.js" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css" rel="stylesheet" type="text/css" media="all" />
    @Styles.Render("~/Content/css")
    <script src='@System.Web.Optimization.Scripts.RenderFormat("{0}","~/bundles/jquery")' type="text/javascript"></script>
    <script src='@System.Web.Optimization.Scripts.RenderFormat("{0}","~/bundles/bootstrap")' type="text/javascript" defer></script>
    <script src='@System.Web.Optimization.Scripts.RenderFormat("{0}","~/bundles/modernizr")' type="text/javascript" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/elevatezoom/3.0.8/jquery.elevatezoom.min.js" type="text/javascript" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js" type="text/javascript" defer></script>
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        const accountID = @Html.Raw(accountID);
        const antiForgeryToken = @Html.Raw(antiForgeryToken);
    </script>
</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
    </div>
    @Html.Action("Index", "Footer")

    @if (Utl.IsLoggedIn(Session)) { 
        @Html.Partial("_CartModal")
    }

    @Html.Partial("_ContactModal")

    <!-- Facebook API - Scripts -->
    <script type="text/javascript" src="/Scripts/facebook.js"></script>
</body>
</html>

Views/Shared/_LoginModal.cshtml
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="LoginLabel" aria-hidden="true">
    <div class="modal-dialog login" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="login-title">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form>
                <div class="card-body">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-user text-info"></i></span>
                        </div>
                        <input type="email" autofocus class="form-control" name="email" placeholder="Email address">
                    </div>
                    <span class="help-block"></span>

                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-lock text-info"></i></span>
                        </div>
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>

                    <div class="alert alert-danger" id="alert-login" role="alert">
                        Couldn't login with the details provided.
                    </div>
                </div>

                <div class="modal-footer">
                    <button id="login-btn" class="btn btn-lg btn-primary btn-block mt-3" type="submit">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#alert-login').hide()
    $('#login-btn').click(function (e) {
        e.preventDefault();
        e.stopPropagation();

        let email = $('input[name="email"]');
        let password = $('input[name="password"]');
        $.post('/Accounts/Login', { email: email.val(), password: password.val() })
            .done(function () {
                window.location.href = "/";
            })
            .fail(function () {
                email.val('');
                password.val('');
                email.select();
                $('#alert-login').show();
            });
    });
</script>

Views/Shared/_Map.cshtml
<div class="col">
    <div class="mapouter">
        <div class="gmap_canvas">
            <iframe width="500" height="200" id="gmap_canvas-@Model"
                    src="https://maps.google.com/maps?q=@Model&t=&z=13&ie=UTF8&iwloc=&output=embed"
                    frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        </div>
    </div>
</div>

Views/Shared/_Navbar.cshtml
@using Patisserie.Controllers

@{
    char at = '@';
}

<nav class="navbar bg-secondary">
    <div class="container p-0">
        <div class="navbar-header align-self-start">
            @Html.ActionLink("Noalek", "Index", "Home", new { area = "" }, new { @class = "navbar-brand logo" })
        </div>
        <div class="nav navbar-nav">
            <ul class="align-items-center btn-group" style="list-style: none;">
                
                <li class="nav-item">
                    <div class="btn-group">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Site Nevigation
                        </button>
                        <div class="dropdown-menu dropdown-menu-right bg-secondary">
                            <a class="dropdown-item row mr-0 ml-0" href="/Branches">
                                <i class="fa fa-map-marker" style="width: 20px;" aria-hidden="true"></i>
                                <span class="col-10">Branches</span>
                            </a>
                            <a class="dropdown-item row mr-0 ml-0" href="/Products">
                                <img src="~/Media/Images/cake-pop.svg" alt="Products" height="20" width="20" />
                                <span class="col-10">Products</span>
                            </a>
                            <a class="dropdown-item row mr-0 ml-0" href="/Categories">
                                <img src="~/Media/Images/grid.svg" alt="Categories" height="20" width="20" />
                                <span class="col-10">Categories</span>
                            </a>
                            @if (Utl.IsAdmin(Session))
                            {
                                <div class="dropdown-divider"></div>
                                <h6 class="dropdown-header text-white-50">Admin Panel</h6>
                                <a class="dropdown-item row mr-0 ml-0" href="/Accounts">
                                    <i class="fa fa-users" aria-hidden="true"></i>
                                    <spoan class="col-10">Accounts</spoan>
                                </a>
                                <a class="dropdown-item row mr-0 ml-0" href="/Home/Admin">
                                    <i class="fa fa-pie-chart" aria-hidden="true"></i>
                                    <span class="col-10">Control Panel</span>
                                </a>
                            }
                        </div>
                    </div>
                </li>
                
                <li class="nav-item" style="display: flex;">
                    <button class="mail-icon-wrapper p-0" type="button" title="Contact Us" data-toggle="modal" data-target="#contact-modal">
                        <div class="mail">
                            <div class="cover"> </div>
                            <div class="letter"><h5>@at</h5></div>
                        </div>
                    </button>
                </li>
                @if (Utl.IsLoggedIn(Session))
                {
                    <li class="nav-item"><button class="cart-btn" type="button" data-toggle="modal" data-target="#cart-modal"><i class="fa fa-shopping-cart cart-icon" aria-hidden="true"><span class="badge badge-notify cart-badge"></span></i></button></li>
                    <li class="nav-item"><a href="/Accounts/Details"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                    <li class="nav-item"><a href="/Accounts/Logout" class="btn btn-outline-secondary">Log-out</a></li>
                }
                else
                {
                    <li class="nav-item"><button class="register-btn" 
                                data-toggle="modal" data-target="#register-modal">Register</button></li>
                    <li class="nav-item"><button class="btn btn-secondary" 
                                data-toggle="modal" data-target="#login-modal">Login</button></li>
                }
            </ul>
        </div>
    </div>
</nav>

@if (!Utl.IsLoggedIn(Session))
{
    @Html.Partial("_LoginModal")
    @Html.Partial("_RegisterModal")
}

Views/Shared/_ProductCard.cshtml
@model Patisserie.Models.Product

<div class="col-12 col-md-4 card promoting-card px-0 product-card" data-price="@Model.Price" data-popularity="@Model.PopularityRate">
    <a href="/Products/Details/@Model.ProductID">
        <div class="card-header" style="min-height: 90px;">
            <h4 class="card-title font-weight-bold mb-2">@Model.Name</h4>
            <h6>
                @if (Model.IsDairy)
                {
                    <span class="badge badge-pill badge-light">Dairy</span>
                }
                @if (Model.IsGlutenFree)
                {
                    <span class="badge badge-pill badge-info">Gluten-free</span>
                }
                @if (Model.IsVegan)
                {
                    <span class="badge badge-pill badge-success">Vegan</span>
                }
            </h6>
        </div>

        <div class="product-show align-self-end">
            <img class="card-img rounded-0 card-img-bottom product-img" src="@Model.ImagePath" alt="@Model.Name">
            <h3 class="product-price">
                <span class="money badge badge-warning text-white">$@Html.DisplayFor(model => model.Price)</span>
            </h3>
        </div>
    </a>
    @if (Patisserie.Controllers.Utl.IsLoggedIn(Session))
    {
        <div class="card-footer">
            <div class="add">
                <button type="submit" class="btn btn-success w-100 add-item-btn"
                        data-id="@Model.ProductID" data-name="@Model.Name"
                        data-description="@Model.Description" data-price="@Model.Price"
                        data-image="@Model.ImagePath">
                    <i class="fas fa-shopping-bag"></i>
                    <span class="list-cart-title cart-title">Add to cart</span>
                </button>
            </div>
            @if (Patisserie.Controllers.Utl.IsAdmin(Session))
            {                        
                <button type="submit" id="BoostProduct" 
                        class="btn btn-default w-100 border-info mt-2" 
                        onclick="boostAProduct('@Model.Name', '@Model.ImagePath')">
                    <i class="fab fa-facebook"></i>
                    <span class="list-cart-title">Boost</span>
                </button>
            }
        </div>
    }
</div>

Views/Shared/_RegisterModal.cshtml
<div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="RegisterLabel" aria-hidden="true">
    <div class="modal-dialog login" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="register-title">Register</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form>
                <div class="modal-body">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-user text-info"></i></span>
                        </div>
                        <input type="email" class="form-control" name="Email" placeholder="Email address">

                        <div class="alert alert-danger col-12" id="bad-email" role="alert">
                        </div>
                    </div>
                    <span class="help-block"></span>

                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-lock text-info"></i></span>
                        </div>
                        <input type="password" class="form-control" name="Password" placeholder="Password">

                        <div class="alert alert-danger col-12" id="bad-password" role="alert">
                        </div>
                    </div>

                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-home text-info"></i></span>
                        </div>
                        <input type="text" class="form-control" name="Address" placeholder="Address">

                        <div class="alert alert-danger col-12" id="bad-address" role="alert">
                        </div>
                    </div>

                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-phone text-info"></i></span>
                        </div>
                        <input type="text" class="form-control" name="PhoneNumber" placeholder="Phone number">

                        <div class="alert alert-danger col-12" id="bad-phone" role="alert">
                        </div>
                    </div>

                    <div class="alert alert-danger col-12" id="alert-register" role="alert">
                        Couldn't register.
                    </div>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-lg btn-primary btn-block mt-3" id="register-btn" type="submit">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.alert').hide()
    $('#register-btn').click(function (e) {
        e.preventDefault();
        e.stopPropagation();

        const email = $('input[name="Email"]');
        const password = $('input[name="Password"]');
        const address = $('input[name="Address"]');
        const phoneNumber = $('input[name="PhoneNumber"]');

        function clearRegisterFields() {
            email.val('');
            password.val('');
            address.val('');
            phoneNumber.val('');
            email.select();
        }

        function printRegisterErrors(data) {
            clearRegisterFields();

            $emailMsg = data.find(e => e.email);
            $passwordMsg = data.find(e => e.password);
            $addressMsg = data.find(e => e.address);
            $phoneMsg = data.find(e => e.phoneNumber);

            if ($emailMsg) {
                $('#bad-email').show()
                $('#bad-email').text($emailMsg.email);
            }
            if ($passwordMsg) {
                $('#bad-password').show()
                $('#bad-password').text($passwordMsg.password);
            }
            if ($addressMsg) {
                $('#bad-address').show()
                $('#bad-address').text($addressMsg.address);
            }
            if ($phoneMsg) {
                $('#bad-phone').show()
                $('#bad-phone').text($phoneMsg.phoneNumber);
            }
        }


        $.post('/Accounts/Register', { email: email.val(), password: password.val(), address: address.val(), phoneNumber: phoneNumber.val() })
            .done(function (data) {
                $('.alert').hide();
                if (!Array.isArray(data)) document.write(data);
                else printRegisterErrors(data);
            })
            .fail(function (e) {
                console.log(e);

                printRegisterErrors(e);
                $('#alert-register').show();
            });

    });

</script>