Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Patisserie.Models
{
    public class Branch
    {
        [Key]
        public int BranchID { get; set; }

        [Required]
        [StringLength(50)]
        [Index(IsUnique = true)]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        [Index(IsUnique = true)]
        public string Address { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set;  }
    }
}

Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Patisserie.Data;
using Patisserie.Models;

namespace Patisserie.Controllers
{
    public class BranchesController : Controller
    {
        private PatisserieContext db = new PatisserieContext();

        // GET: Branches
        public ActionResult Index()
        {
            return View(db.Branches.ToList());
        }

        // GET: Branches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // GET: Branches/Create
        public ActionResult Create()
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BranchID,Name,Address,PhoneNumber")] Branch branch)
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            bool isNameInDB = db.Branches.Any(a => a.Name == branch.Name && a.BranchID != branch.BranchID);
            bool isAddressInDB = db.Branches.Any(a => a.Address == branch.Address && a.BranchID != branch.BranchID);

            if (ModelState.IsValid && !isAddressInDB && !isNameInDB)
            {
                db.Branches.Add(branch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (isNameInDB)
                ViewBag.isNameInDB = isNameInDB;
            if (isAddressInDB)
                ViewBag.isAddressInDB = isAddressInDB;

            return View(branch);
        }

        // GET: Branches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BranchID,Name,Address,PhoneNumber")] Branch branch)
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            bool isNameInDB = db.Branches.Any(a => a.Name == branch.Name && a.BranchID != branch.BranchID);
            bool isAddressInDB = db.Branches.Any(a => a.Address == branch.Address && a.BranchID != branch.BranchID);

            if (ModelState.IsValid && !isAddressInDB && !isNameInDB)
            {
                db.Entry(branch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (isNameInDB)
                ViewBag.isNameInDB = isNameInDB;
            if (isAddressInDB)
                ViewBag.isAddressInDB = isAddressInDB;

            return View(branch);
        }

        // POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!Utl.IsAdmin(Session))
                return RedirectToAction("Index", "Home");

            Branch branch = db.Branches.Find(id);

            db.Branches.Remove(branch);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Branches/Create.cshtml
@model Patisserie.Models.Branch

@{
    ViewBag.Title = "Create a New Branch";
}

<div class="row justify-content-between">
    <h1 class="my-4">@ViewBag.Title</h1>
    <span class="col-4 d-flex flex-row-reverse align-items-center">
        @Html.ActionLink("Back to Branches List", "Index", null, new { @class = "btn btn-outline-secondary" })
    </span>
</div>
<hr class="accessory" />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group form-row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.isNameInDB != null && ViewBag.isNameInDB == true)
            {
                <div class="text-danger offset-2 col-8">
                    Name is already in use.
                </div>
            }
        </div>

        <div class="form-group form-row">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.isAddressInDB != null && ViewBag.isAddressInDB == true)
            {
                <div class="text-danger offset-2 col-8">
                    Address is already in use.
                </div>
            }
        </div>

        <div class="form-group form-row">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Branches/Details.cshtml
@model Patisserie.Models.Branch

@{
    ViewBag.Title = Model.Name;
}

<div class="row justify-content-between">
    <h1 class="my-4">@ViewBag.Title</h1>

    <span class="col-4 d-flex flex-row-reverse align-items-center">
        @if (Patisserie.Controllers.Utl.IsAdmin(Session))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.BranchID }, new { @class = "btn btn-primary" })
        }
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-outline-secondary", style = "margin-right: 1em;" })
    </span>
</div>

<hr class="accessory" />


<div class="row">
    @Html.Partial("_Map", Model.Address)
    <dl class="dl-horizontal col-12 col-md-6">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>
</div>

Views/Branches/Edit.cshtml
@model Patisserie.Models.Branch

@{
    ViewBag.Title = "Edit";
}

<div class="row justify-content-between">
    <h1 class="my-4">@ViewBag.Title</h1>

    <span class="col-4 d-flex flex-row-reverse align-items-center">
        @Html.ActionLink("Back to Branch Page", "Details", "Branches", new { id = Model.BranchID }, new { @class = "btn btn-outline-secondary" })
    </span>
</div>

<hr class="accessory" />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BranchID)

        <div class="form-group form-row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.isNameInDB != null && ViewBag.isNameInDB == true)
            {
                <div class="text-danger offset-2 col-8">
                    Name is already in use.
                </div>
            }
        </div>

        <div class="form-group form-row">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.isAddressInDB != null && ViewBag.isAddressInDB == true)
            {
                <div class="text-danger offset-2 col-8">
                    Address is already in use.
                </div>
            }
        </div>

        <div class="form-group form-row">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Branches/Index.cshtml
@model IEnumerable<Patisserie.Models.Branch>

@{
    ViewBag.Title = "Branches";
}

<div class="row justify-content-between">
    <h1 class="col my-4">@ViewBag.Title</h1>
    @if (Patisserie.Controllers.Utl.IsAdmin(Session))
    {
        <span class="col-4 d-flex flex-row-reverse align-items-center">
            @Html.ActionLink("Create New Branch", "Create", null, new { @class = "btn btn-outline-primary" })
        </span>
    }
</div>

<hr class="accessory" />

<table class="table" id="branches">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        @if (Patisserie.Controllers.Utl.IsAdmin(Session))
        {
        <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr class="branch" data-id="@item.BranchID">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            @if (Patisserie.Controllers.Utl.IsAdmin(Session))
            {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BranchID }, new { @class = "btn btn-secondary" })
                <button class="btn btn-danger btn-delete"
                        data-name="@item.Name" data-id="@item.BranchID">
                    Delete
                </button>
            </td>
            }
        </tr>
    }

</table>

@Html.Partial("_DeleteModal", null, new ViewDataDictionary { { "title", "name" }, { "category", "Branches" } })

<script type="text/javascript">
    $(".branch").click(function (e) {
        window.location = window.location.href + "/Details/" + $(this).data("id");
    });
</script>